services:
    aww:
        build:
            context: .
            dockerfile: Dockerfile
            tags:
                - itskdhere/aww:2.1.3
                - itskdhere/aww:latest
        container_name: aww
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
            - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
            - WEBHOOK_ID=${WEBHOOK_ID}
            - WEBHOOK_TOKEN=${WEBHOOK_TOKEN}
            - HTTP_SERVER=${HTTP_SERVER}
            - PORT=${PORT}
            - CAT_API_KEY=${CAT_API_KEY}
            - DOG_API_KEY=${DOG_API_KEY}
        ports:
            - ${PORT}:${PORT}
        networks:
            - default
